//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Midheaven.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int M_ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string RealName { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public string PhoneNum { get; set; }
        public string Address { get; set; }
        public Nullable<int> R_ID { get; set; }
        public Nullable<int> M_Flog { get; set; }
    }
}
